seed: 42
device: "auto"

data:
  dataset: "CelebA"
  shift_type: "confounder"
  target_name: "Male"
  confounder_names: ["Young"]
  root_dir: "./celebA/data/"
  fraction: 1.0
  val_fraction: 0.1
  batch_size: 32
  num_workers: 4
  reweight_groups: false
  augment_data: false

model:
  name: "resnet18"
  train_from_scratch: false

training:
  n_epochs: 50
  lr: 0.0001
  weight_decay: 0.0001
  scheduler: false
  gamma: 0.1

robustness:
  robust: false

logging:
  log_dir: "./logs/celeba_resnet50_erm"
  log_every: 50
  save_step: 10
  save_best: true
  save_last: true
  show_progress: true
  resume: false
